In [ ]:
import numpy as np

def get_moves(m,n):
    
    #this gives us a 8x8 matrix where, for each position m,n the queen can be in the chessboard
    #valid moves from that position will be 1, and the rest 0
    
    matrix = np.zeros((8, 8))
    matrix[m,:] = 1
    matrix[:,n] = 1
    for i in range(-7,8):
        if m+i < 8 and m+i >= 0 and n+i < 8 and n+i >= 0:
            matrix[m+i,n+i] = 1
        if m+i < 8 and m+i >= 0 and n-i < 8 and n-i >= 0:
            matrix[m+i,n-i] = 1
    matrix[m,n] = 0
    
    return matrix

In [ ]:
print(get_moves(3,4))

[[0. 1. 0. 0. 1. 0. 0. 1.]
 [0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 0. 0. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 0. 0.]
 [0. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 0. 1. 0. 0. 1.]
 [1. 0. 0. 0. 1. 0. 0. 0.]]


In [ ]:
def transition_row(m,n):   #this converts the 8x8 matrix into a 64x1 row vector, which represents a row in the transition matrix
    
    T_row = get_moves(m,n).flatten()
    T_row /= sum(T_row)
    
    return T_row


T = []   # We define T as the transtion matrix for all 64 squares on the chessboard, starting from (0,0), (0,1)... to (7,7)

for i in range(8):
    for j in range(8):
        T.append(transition_row(i,j))

T = np.array(T)

In [ ]:
def probability_of_returning(max_number_of_moves):
    
    start_position = 7 * 8 + 3    # Index of the queen's starting position in the 64x1 array
    
    init = np.zeros((1,64))       # Here the initial state is given by a 1x64 column vector
    init[0][start_position] = 1   # Now we set the standard starting position of the queen, as the initial state

    P = 0   #Initialize the probability of returning to starting position
    state = init   #Set the state to Initial state

    for i in range(1,max_number_of_moves):
        
        state_i = np.dot(state, T)
        
        P += i * state_i[0] [start_position]
        state_i[0] [start_position] = 0   # Removing cases where the quuen has returned to her starting position

        state = state_i   # Change the state to the i th state

    return P

In [ ]:
probability_of_returning(100000)

In [ ]:
import matplotlib.pyplot as plt

x = [i for i in range(1000)]
y = [probability_of_returning(i) for i in x]

plt.plot(x, y)
plt.xlabel('Max number of moves')
plt.ylabel('Average moves to reach initial position')
plt.show()